language: python

python:
  - "3.6"
  - "3.7"

dist: xenial
sudo: false

services:
- docker

before_install:
  - git clone https://github.com/DEX-Company/barge.git
  - cd barge
  - git checkout tags/dex-2019-01-30
  - git pull
  - bash -x start_ocean.sh --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - sleep 15

install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Generate PYPI package on tagged versions on master
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/ocean-py
    python: 3.6
