language: python
python:
- '3.6'
- '3.7'
dist: xenial
sudo: true
addons:
  ssh_known_hosts: shrimp.octet.services
services:
- docker
before_install:
# - export BARGE_URL=http://52.187.164.74
# - scripts/setup_for_remote_barge.sh $BARGE_URL
- export BARGE_URL=http://localhost
- scripts/setup_for_local_barge.sh

install: pip install -U tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: "${PYPI_USER}"
  password: "${PYPI_PASSWORD}"
  skip_cleanup: true
  on:
    tags: true
    repo: DEX-Company/starfish-py
    python: 3.6
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy
  on:
    tags: true
    repo: DEX-Company/starfish-py
    all_branches: true
#    - branch: feature/deploy-docs
#    - branch: develop
    python: 3.6
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
  on:
    tags: false
    repo: DEX-Company/starfish-py
    all_branches: true
    python: 3.6
