language: python
python:
- '3.6'
- '3.7'
dist: xenial
sudo: true
addons:
  ssh_known_hosts: shrimp.octet.services
services:
- docker
before_install:
# - export BARGE_URL=http://52.187.164.74
# - scripts/setup_for_remote_barge.sh $BARGE_URL
- export BARGE_URL=http://localhost
- scripts/setup_for_local_barge.sh

install: pip install -U tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: "${PYPI_USER}"
  password: "${PYPI_PASSWORD}"
  skip_cleanup: true
  on:
    tags: true
    repo: DEX-Company/starfish-py
    python: 3.6
- provider: pages
  local_dir: docs/build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    tags: true
    repo: DEX-Company/starfish-py
    all_branches: true
    python: 3.6
