language: python
python:
- '3.6'
- '3.7'
dist: xenial
sudo: false
addons:
  ssh_known_hosts: shrimp.octet.services
services:
- docker
before_install:
# NOTE: if you change the barge_url, you also need to change the url in tox
- scripts/setup_for_remote_barge.sh http://52.187.164.74
install: pip install -U tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: "${PYPI_USER}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
    repo: DEX-Company/starfish-py
    python: 3.6
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy
  on:
    tags: true
    repo: DEX-Company/starfish-py
    all_branches: true
#    - branch: feature/deploy-docs
#    - branch: develop
    python: 3.6
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
  on:
    tags: false
    repo: DEX-Company/starfish-py
    all_branches: true
    python: 3.6
