name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.483'
    - name: Install dependencies
      run: make install IGNORE_VENV=1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Lint
      run: make lint
    - name: Install Surfer
      uses: actions/checkout@v2
      with:
        repository: DEX-Company/surfer
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: develop
        path: surfer
    - name: Install dex-chain
      uses: actions/checkout@v2
      with:
        repository: DEX-Company/dex-chain
        ref: master
        path: dex-chain
    - name: Start dex-chain
      run: |
        docker login docker.pkg.github.com --username billbsing --password ${{ secrets.ACCESS_PACKAGES }}
        cd ../dex-chain
        ./start_dex_chain.sh test &
    - name : Start Surfer
      run: |
        cd ../surfer
        clojure -M:main &
        scripts/wait_for_surfer.sh
    - name: Allow Docker access to github packages
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}
    - name: Deploy convex-contracts
      run: docker run docker.pkg.github.com/dex-company/convex-contracts/deploy-testing:latest
    - name: Test
      run: make tests
