name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.483'
    - name: Install dependencies
      run: make install-test IGNORE_VENV=1
    - name: Lint
      run: make lint
    - name: Install Surfer
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/surfer
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: develop
        path: surfer
    - name: Install Barge
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/barge
        # ref: tags/dex-2019-10-09
        ref: develop
        path: barge
    - name: Start Barge
      run: |
        cd ../barge
        sudo sysctl -w vm.max_map_count=262144
        ./start_ocean.sh --no-brizo --no-surfer --no-koi --local-spree-node &
        sleep 240
    - name : Start Surfer
      run: |
        cd ../surfer
        clojure -M:main &
    - name: Wait for barge startup
      run: scripts/wait_for_migration_and_extract_keeper_artifacts.sh
    - name: Test
      run: make test
